name: CI Checks On Push

on: push

jobs:
  precommit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install black pytest

      - name: Run Tests
        run: pytest -s -v

      - name: Check if .py scripts is properly formatted in Black 
        run: black --check ./streamlit        
