name: CI Checks On Push

on: push

jobs:
  test-in-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Test Env
        run: docker-compose -f 'docker-compose.ci.yaml' up --exit-code-from test-d2d
